# Generated by Django 4.2.4 on 2023-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isLawyer',
            new_name='Client',
        ),
        migrations.AddField(
            model_name='profile',
            name='Lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
