# Generated by Django 4.2.4 on 2023-09-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_islawyer_profile_client_profile_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
    ]
