# Generated by Django 4.2.4 on 2023-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_lawyer_specialties_lawyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='areasOfExpertise',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
