# Generated by Django 4.2.4 on 2023-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_clients_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
