# Generated by Django 4.2.4 on 2023-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_lawyer_address_alter_lawyer_areasofexpertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='averageRating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='hourlyRate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='yearsOfExperience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
