# Generated by Django 4.2.4 on 2023-08-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_lawyers_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyers',
            name='number',
        ),
    ]
