# Generated by Django 4.2.4 on 2023-09-01 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0005_remove_lawyers_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base_app.profile'),
        ),
        migrations.AddField(
            model_name='lawyers',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base_app.profile'),
        ),
    ]
