# Generated by Django 4.2.4 on 2023-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_lawyer_averagerating_alter_lawyer_hourlyrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='yearsOfExperience',
            field=models.PositiveIntegerField(default=0, max_length=80),
        ),
    ]
