# Generated by Django 4.2.4 on 2023-10-01 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_lawyer_yearsofexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='averageRating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='hourlyRate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lisenceStatus',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('revoked', 'revoked')], default=('active', 'active'), max_length=20, null=True),
        ),
    ]
