# Generated by Django 4.2.4 on 2023-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_lawyer_averagerating_alter_lawyer_hourlyrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='areasOfExpertise',
            field=models.TextField(null=True),
        ),
    ]
