# Generated by Django 4.2.4 on 2023-10-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_lawyer_areasofexpertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingTime', models.DateTimeField(null=True)),
                ('endingTime', models.DateField(null=True)),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='base_app.lawyer')),
            ],
        ),
    ]
