# Generated by Django 4.2.4 on 2023-10-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_availablehours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablehours',
            old_name='endingTime',
            new_name='ending_time',
        ),
        migrations.RenameField(
            model_name='availablehours',
            old_name='startingTime',
            new_name='starting_time',
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('starting_time', models.DateTimeField(null=True)),
                ('ending_time', models.DateField(null=True)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.availablehours')),
            ],
        ),
    ]
