# Generated by Django 4.2.4 on 2023-10-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_rename_endingtime_availablehours_ending_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablehours',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.lawyer'),
        ),
    ]
