# Generated by Django 4.2.4 on 2023-11-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_appointments_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.profile'),
        ),
    ]
