# Generated by Django 4.2.4 on 2023-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_alter_lawyer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
