# Generated by Django 4.2.4 on 2023-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='images/profile-pics/'),
        ),
    ]
