# Generated by Django 4.2.4 on 2023-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
