# Generated by Django 4.2.4 on 2023-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_messages_checked_messages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='informed_client',
            field=models.BooleanField(default=False),
        ),
    ]
