# Generated by Django 4.2.4 on 2023-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0027_appointments_informed_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
