# Generated by Django 4.2.4 on 2023-11-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0028_rating_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.client'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.client'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lawyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.lawyer'),
        ),
    ]
