# Generated by Django 4.2.4 on 2023-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0029_alter_appointments_client_alter_rating_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile-pics/avatar.png', null=True, upload_to='images/profile-pics/'),
        ),
    ]
