# Generated by Django 4.2.4 on 2023-11-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0030_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='averageRating',
        ),
    ]
