# Generated by Django 4.2.4 on 2023-11-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0031_remove_lawyer_averagerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Client',
            new_name='isClient',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Lawyer',
            new_name='isLawyer',
        ),
        migrations.AlterField(
            model_name='rating',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.client'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.lawyer'),
        ),
    ]
