# Generated by Django 4.2.4 on 2023-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_rename_client_profile_isclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
